# Generated by Django 4.1 on 2022-08-21 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('score', models.PositiveIntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Very good')], default=3, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog', verbose_name='Blog')),
            ],
        ),
    ]
