# Generated by Django 4.1 on 2022-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='t@t.t', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='t', max_length=50, verbose_name='Full name'),
        ),
    ]
