# Generated by Django 4.1 on 2022-09-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
