# Generated by Django 4.1 on 2022-08-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('publish_blog', 'Can publish blog')], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
