# Generated by Django 4.1 on 2022-08-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ipaddress_ip'),
        ('blogs', '0003_blogip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.ManyToManyField(related_name='blogs', through='blogs.BlogIp', to='accounts.ipaddress'),
        ),
    ]
