# Generated by Django 4.1 on 2022-09-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_hits_alter_blogip_blog_alter_blogip_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-datetime_modified'], 'permissions': [('publish_blog', 'Can publish blog')], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
