# Generated by Django 4.1 on 2022-08-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='Ip address'),
        ),
    ]
